name: minha_escola
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: 0.12.0+4
  dio: 3.0.9
  flutter_secure_storage: 3.3.1+1
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  shared_preferences: 0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
  #  - images/a_dot_ham.jpeg
  fonts: 
    - family: Montserrat
      fonts:
        - asset: assets/montserrat/Montserrat-Regular.ttf
